React
vamsisollem/Fundamentals pull request #2
Opened 2024-11-20 20:06 UTC by vamsisollem

To-do with react

2024-11-20 22:13 UTC, banavasi commented on src/App.jsx
> +      async function postData() {
this can be a separate method. and call postData(taskName)

2024-11-25 22:56 UTC, banavasi requested changes

2024-11-25 22:56 UTC, banavasi commented on vite.config.js
Add path alias, where you can use @ or ~ to access src files

2024-11-25 22:56 UTC, banavasi commented on src/App.jsx
> +import Header from './components/header';
use path alias, meaning access header components you need to use @/components/header

2024-11-25 22:56 UTC, banavasi commented on src/components/header.css
All this css can be incorporated with tailwind. width: 300px; can be w-[300px]

2024-11-25 22:56 UTC, banavasi commented on src/components/header.jsx
> +import './header.css'
I think this is redundant

2024-11-25 22:56 UTC, banavasi commented on src/components/task.jsx
> +import './task.css';
This seems redundant.

2024-11-26 01:47 UTC, vamsisollem commented on src/components/task.jsx
> +import './task.css';
Do you want me to use header and task in the app itself ?

2024-12-06 17:20 UTC, banavasi approved these changes

2024-12-06 17:20 UTC, banavasi commented on package.json
why do you have so many dependencies?

2024-12-06 17:20 UTC, banavasi commented on src/components/task.jsx
>              type="checkbox"
You can create a BaseInput component. Probably try using styled components

2024-12-06 17:20 UTC, merged